--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: mongo-express
  name: mongo-express
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: mongo-express
  template: 
    metadata: 
      labels: 
        app: mongo-express
    spec: 
      containers: 
        - 
          env: 
            - 
              name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom: 
                secretKeyRef: 
                  key: mongo-username
                  name: mongodb-secret
            - 
              name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: mongo-password
                  name: mongodb-secret
            - 
              name: ME_CONFIG_MONGODB_SERVER
              valueFrom: 
                configMapKeyRef: 
                  key: database_url
                  name: mongo-config
          image: mongo-express
          name: mongo-express
          ports: 
            - 
              containerPort: 8081

